const menu = [
    {
        id: 1,
        title: "Dhido",
        category: "Lunch",
        price: 200,
        img: './images/dhido.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 2,
        title: "Yomari",
        category: "Snacks",
        price: 100,
        img: './images/yomari.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 3,
        title: "Daal Bhat Tarkari",
        category: "Dinner",
        price: 150,
        img: './images/daalBhat.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 4,
        title: "Momo",
        category: "Lunch",
        price: 150,
        img: './images/momo.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 5,
        title: "Samaybaji",
        category: "Lunch",
        price: 200,
        img: './images/newariSet.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 6,
        title: "Juju Dhau",
        category: "Drinks",
        price: 100,
        img: './images/jujuDhau.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 7,
        title: "Kwati",
        category: "Snacks",
        price: 50,
        img: './images/kwati.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 8,
        title: "Selroti",
        category: "Snacks",
        price: 30,
        img: './images/selroti.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 9,
        title: "Chatamari",
        category: "Snacks",
        price: 100,
        img: './images/chatamari.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 10,
        title: "Laphing",
        category: "Snacks",
        price: 100,
        img: './images/laphing.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
    {
        id: 11,
        title: "Lassi",
        category: "Drinks",
        price: 120,
        img: './images/lassi.jpg',
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas nulla quidem eveniet placeat expedita perferendis quas praesentium ipsum eius maiores?",
    },
]