const menu = [
    {
        id: 1,
        title: "sandwich",
        category: "breakfast",
        price: 15.99,
        img: './food.jpg',
        desc: "Food description",
    },
    {
        id: 2,
        title: "Toast",
        category: "breakfast",
        price: 15.99,
        img: './food.jpg',
        desc: "Food description",
    },
    {
        id: 3,
        title: "Bhat",
        category: "dinner",
        price: 15,
        img: './food.jpg',
        desc: "Food description",
    },
    {
        id: 4,
        title: "momo",
        category: "lunch",
        price: 15.99,
        img: './food.jpg',
        desc: "Food description",
    },
    {
        id: 5,
        title: "pancakes",
        category: "lunch",
        price: 20,
        img: './food.jpg',
        desc: "Food description",
    },
    {
        id: 6,
        title: "lassi",
        category: "shake",
        price: 100,
        img: './food.jpg',
        desc: "Food description",
    },
]